service: aaaAcademy
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  profile: serverlessUser
  region: eu-north-1
  iam:
    role: arn:aws:iam::990371472798:role/course-role

plugins:
  - serverless-webpack

package:
  individually: true

functions:
  getAllSessions:
    handler: functions/Session/getAllSessions.handler
    events:
      - httpApi:
          path: '/api/session'
          method: GET
  bookSession:
    handler: functions/Session/bookSession.handler
    events:
      - httpApi:
          path: '/api/session/{sessionID}'
          method: PUT
  cancelSession:
    handler: functions/Session/cancelSession.handler
    events:
      - httpApi:
          path: '/api/session/cancel/{sessionID}'
          method: PUT
  getMySession:
    handler: functions/Session/getMySession.handler
    events:
      - httpApi:
          path: '/api/session/{sessionID}'
          method: GET
  getAllMySessions:
    handler: functions/Session/getAllMySessions.handler
    events:
      - httpApi:
          path: '/api/session/mySessions'
          method: GET
  editMySession:
    handler: functions/Session/editMySession.handler
    events:
      - httpApi:
          path: '/api/session/edit'
          method: PUT
  addSessions:
    handler: functions/Session/addSessions.handler
    events:
      - httpApi:
          path: '/api/session/add'
          method: POST
  deleteSession:
    handler: functions/Session/deleteSession.handler
    events:
      - httpApi:
          path: '/api/session/delete/{sessionID}'
          method: DELETE
  signup:
    handler: functions/User/signup.handler
    events:
      - httpApi:
          path: '/api/auth/signup'
          method: POST
  login:
    handler: functions/User/login.handler
    events:
      - httpApi:
          path: '/api/auth/login'
          method: POST
  changePassword:
    handler: functions/User/changePass.handler
    events:
      - httpApi:
          path: '/api/auth/changePassword'
          method: PUT
  changeInfo:
    handler: functions/User/changeInfo.handler
    events:
      - httpApi:
          path: '/api/auth/changeInfo'
          method: PUT
  logout:
    handler: functions/User/logout.handler
    events:
      - httpApi:
          path: '/api/auth/logout'
          method: POST
  approveUser:
    handler: functions/User/approveUser.handler
    events:
      - httpApi:
          path: '/api/User/approveUser'
          method: POST
  
resources:
  Resources:
    aaaAcademyDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: sessionsDB
        AttributeDefinitions:
          - AttributeName: sessionID
            AttributeType: S
        KeySchema:
          - AttributeName: sessionID
            KeyType: HASH # Partition key/Primary key

        BillingMode: PAY_PER_REQUEST

    userDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: academyUserDB
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH # Partition key/Primary key

        BillingMode: PAY_PER_REQUEST

    pendingUserDB:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: pendingUserDB
        AttributeDefinitions:
          - AttributeName: PK
            AttributeType: S
        KeySchema:
          - AttributeName: PK
            KeyType: HASH # Partition key/Primary key

        BillingMode: PAY_PER_REQUEST